Sync develop changes with master
rsksmart/rif-marketplace-dev pull request #126
Opened 2021-04-08 07:00 UTC by artem-brazhnikov

2021-04-08 10:30 UTC, nduchak approved these changes

2021-04-08 10:31 UTC, nduchak requested changes
But should we sync develop from master instead?

2021-04-08 11:08 UTC, nduchak approved these changes

2021-04-27 09:13 UTC, artem-brazhnikov commented
> But should we sync develop from master instead?

there is nothing to merge from master now

2021-05-11 10:24 UTC, closed without merging